### ISSUE TITLE
Don't automatically select first row in ScrollListStackSelector

### ISSUE THREAD

**Issue by lapp0** [nix-gui/nix-gui#28]

**Comment by Radvendii** [comment]
This seems to be tied to how `QListWidget` works. Even if we add `self.item_list.clearSelection()` or `self.item_list.item(0).setSelected(False)` to the constructor, it doesn't change the behaviour. I know that it's not getting set later on, because setting `self.item_list.item(2).setSelected(True)` does make the 3rd item selected.

It's worth noting though, that there is a difference between an element being **selected** and what happens when the window first opens. The colour gets darker for me when I actually select the first item.

Related issues:
- https://www.qtcentre.org/threads/37982-QListWidget-non-selected-to-start
- https://www.qtcentre.org/threads/43795-QTableWidget-How-to-quot-select-none-quot-with-SingleSelection-mode
  In other contexts, it seems, one can set the selection to an invalid number. I tried setting `self.item_list.setCurrentRow(-1)` and it doesn't do anything.

**Comment by lapp0** [comment]
@Radvendii thanks for researching. Perhaps since this issue isn't really harmful to Nix-Gui and doesn't have an obvious fix it should be closed as will-not-do?
